language: node_js
node_js:
  - 12
services:
    - docker
install:
    - echo "nothing needs to be"
before_script:
    - echo "no tests"
script:
    - docker --version
    - docker build -t udagram-api-user ./udagram-api-user
    - docker tag udagram-api-user namnguyen1997/udagram-api-user:v1
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker tag udagram-api-feed namnguyen1997/udagram-api-feed:v1
    - docker build -t udagram-frontend ./udagram-frontend
    - docker tag udagram-frontend namnguyen1997/udagram-frontend:v1
    - docker build -t reverseproxy ./udagram-reverseproxy
    - docker tag reverseproxy namnguyen1997/reverseproxy:v1
after_success:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker push namnguyen1997/udagram-api-user:v1
    - docker push namnguyen1997/udagram-api-feed:v1
    - docker push namnguyen1997/udagram-frontend:v1
    - docker push namnguyen1997/reverseproxy:v1
    